const std::string Queries::ALTER_PRODUCT_ADD_FOREIGN_KEYS = 
R"(
ALTER TABLE PRODUCT ADD CONSTRAINT fk_product_acquisition_contract
FOREIGN KEY (ACQUISITION_CONTRACT_ID) REFERENCES ACQUISITION_CONTRACT (ID);

ALTER TABLE PRODUCT ADD CONSTRAINT fk_product_sales_contract
FOREIGN KEY (SALES_CONTRACT_ID) REFERENCES SALES_CONTRACT (ID);

ALTER TABLE PRODUCT ADD CONSTRAINT fk_product_transfer
FOREIGN KEY (TRANSFER_ID) REFERENCES TRANSFER (ID);

ALTER TABLE PRODUCT ADD CONSTRAINT fk_product_warehouse
FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE (ID);

ALTER TABLE PRODUCT ADD CONSTRAINT fk_product_product_type
FOREIGN KEY (PRODUCT_TYPE_ID) REFERENCES PRODUCT_TYPE (ID);
)";

const std::string Queries::ALTER_PRODUCT_TYPE_ADD_FOREIGN_KEYS = 
R"(
ALTER TABLE PRODUCT_TYPE ADD CONSTRAINT fk_product_type_manufacturer
FOREIGN KEY (MANUFACTURER_ID) REFERENCES MANUFACTURER (ID);

ALTER TABLE PRODUCT_TYPE ADD CONSTRAINT fk_product_type_category
FOREIGN KEY (PRODUCT_CATEGORY_ID) REFERENCES PRODUCT_CATEGORY (ID);
)";

const std::string Queries::ALTER_PRODUCT_CATEGORY_ADD_FOREIGN_KEYS = 
R"(
-- No foreign keys to add
)";

const std::string Queries::ALTER_REGULATION_ADD_FOREIGN_KEYS = 
R"(
ALTER TABLE REGULATION ADD CONSTRAINT fk_regulation_jurisdiction
FOREIGN KEY (JURISDICTION_ID) REFERENCES JURISDICTION (ID);
)";

const std::string Queries::ALTER_SALES_CONTRACT_ADD_FOREIGN_KEYS = 
R"(
ALTER TABLE SALES_CONTRACT ADD CONSTRAINT fk_sales_contract_purchaser
FOREIGN KEY (PURCHASER_ID) REFERENCES PURCHASER (ID);

ALTER TABLE SALES_CONTRACT ADD CONSTRAINT fk_sales_contract_jurisdiction
FOREIGN KEY (JURISDICTION_ID) REFERENCES JURISDICTION (ID);

ALTER TABLE SALES_CONTRACT ADD CONSTRAINT fk_sales_contract_negotiator
FOREIGN KEY (NEGOTIATOR_ID) REFERENCES NEGOTIATOR (ID);

ALTER TABLE SALES_CONTRACT ADD CONSTRAINT fk_sales_contract_manager
FOREIGN KEY (MANAGER_ID) REFERENCES MANAGER (ID);
)";

const std::string Queries::ALTER_ACQUISITION_CONTRACT_ADD_FOREIGN_KEYS = 
R"(
ALTER TABLE ACQUISITION_CONTRACT ADD CONSTRAINT fk_acquisition_contract_seller
FOREIGN KEY (SELLER_ID) REFERENCES SELLER (ID);

ALTER TABLE ACQUISITION_CONTRACT ADD CONSTRAINT fk_acquisition_contract_jurisdiction
FOREIGN KEY (JURISDICTION_ID) REFERENCES JURISDICTION (ID);

ALTER TABLE ACQUISITION_CONTRACT ADD CONSTRAINT fk_acquisition_contract_negotiator
FOREIGN KEY (NEGOTIATOR_ID) REFERENCES NEGOTIATOR (ID);

ALTER TABLE ACQUISITION_CONTRACT ADD CONSTRAINT fk_acquisition_contract_manager
FOREIGN KEY (MANAGER_ID) REFERENCES MANAGER (ID);
)";

const std::string Queries::ALTER_TRANSFER_ADD_FOREIGN_KEYS = 
R"(
ALTER TABLE TRANSFER ADD CONSTRAINT fk_transfer_origin
FOREIGN KEY (ORIGIN_ID) REFERENCES WAREHOUSE (ID);

ALTER TABLE TRANSFER ADD CONSTRAINT fk_transfer_destination
FOREIGN KEY (DESTINATION_ID) REFERENCES WAREHOUSE (ID);

ALTER TABLE TRANSFER ADD CONSTRAINT fk_transfer_manager
FOREIGN KEY (MANAGER_ID) REFERENCES MANAGER (ID);
)";

const std::string Queries::ALTER_PRODUCT_CAPACITY_ADD_FOREIGN_KEYS = 
R"(
ALTER TABLE PRODUCT_CAPACITY ADD CONSTRAINT fk_product_capacity_product_type
FOREIGN KEY (PRODUCT_TYPE_ID) REFERENCES PRODUCT_TYPE (ID);

ALTER TABLE PRODUCT_CAPACITY ADD CONSTRAINT fk_product_capacity_warehouse
FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE (ID);
)";

const std::string Queries::ALTER_PRODUCT_REGULATION_ADD_FOREIGN_KEYS = 
R"(
ALTER TABLE PRODUCT_REGULATION ADD CONSTRAINT fk_product_regulation_category
FOREIGN KEY (PRODUCT_CATEGORY_ID) REFERENCES PRODUCT_CATEGORY (ID);

ALTER TABLE PRODUCT_REGULATION ADD CONSTRAINT fk_product_regulation_regulation
FOREIGN KEY (REGULATION_ID) REFERENCES REGULATION (ID);
)";

const std::string Queries::ALTER_PURCHASER_ADD_FOREIGN_KEYS = 
R"(
ALTER TABLE PURCHASER ADD CONSTRAINT fk_purchaser_jurisdiction
FOREIGN KEY (JURISDICTION_ID) REFERENCES JURISDICTION (ID);
)";

const std::string Queries::ALTER_SELLER_ADD_FOREIGN_KEYS = 
R"(
ALTER TABLE SELLER ADD CONSTRAINT fk_seller_jurisdiction
FOREIGN KEY (JURISDICTION_ID) REFERENCES JURISDICTION (ID);
)";

const std::string Queries::ALTER_WAREHOUSE_ADD_FOREIGN_KEYS = 
R"(
ALTER TABLE WAREHOUSE ADD CONSTRAINT fk_warehouse_office
FOREIGN KEY (OFFICE_ID) REFERENCES OFFICE (ID);
)";

const std::string Queries::ALTER_MANUFACTURER_ADD_FOREIGN_KEYS = 
R"(
ALTER TABLE MANUFACTURER ADD CONSTRAINT fk_manufacturer_negotiator
FOREIGN KEY (NEGOTIATOR_ID) REFERENCES NEGOTIATOR (ID);
)";

const std::string Queries::ALTER_LOCATION_ADD_FOREIGN_KEYS = 
R"(
-- No foreign keys to add
)";

const std::string Queries::ALTER_OFFICE_ADD_FOREIGN_KEYS = 
R"(
ALTER TABLE OFFICE ADD CONSTRAINT fk_office_location
FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION (ID);

ALTER TABLE OFFICE ADD CONSTRAINT fk_office_jurisdiction
FOREIGN KEY (JURISDICTION_ID) REFERENCES JURISDICTION (ID);

ALTER TABLE OFFICE ADD CONSTRAINT fk_office_overseer
FOREIGN KEY (OVERSEER_ID) REFERENCES MANAGER (ID);
)";

const std::string Queries::ALTER_JURISDICTION_ADD_FOREIGN_KEYS = 
R"(
-- No foreign keys to add
)";

const std::string Queries::ALTER_NEGOTIATOR_ADD_FOREIGN_KEYS = 
R"(
ALTER TABLE NEGOTIATOR ADD CONSTRAINT fk_negotiator_employee
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (ID);
)";

const std::string Queries::ALTER_MANAGER_ADD_FOREIGN_KEYS = 
R"(
ALTER TABLE MANAGER ADD CONSTRAINT fk_manager_employee
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (ID);
)";

const std::string Queries::ALTER_EMPLOYEE_ADD_FOREIGN_KEYS = 
R"(
ALTER TABLE EMPLOYEE ADD CONSTRAINT fk_employee_office
FOREIGN KEY (OFFICE_ID) REFERENCES OFFICE (ID);

ALTER TABLE EMPLOYEE ADD CONSTRAINT fk_employee_schedule
FOREIGN KEY (SCHEDULE_ID) REFERENCES SCHEDULE (ID);

ALTER TABLE EMPLOYEE ADD CONSTRAINT fk_employee_job_position
FOREIGN KEY (JOB_POSITION_ID) REFERENCES JOB_POSITION (ID);

ALTER TABLE EMPLOYEE ADD CONSTRAINT fk_employee_location
FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION (ID);

ALTER TABLE EMPLOYEE ADD CONSTRAINT fk_employee_jurisdiction
FOREIGN KEY (JURISDICTION_ID) REFERENCES JURISDICTION (ID);

ALTER TABLE EMPLOYEE ADD CONSTRAINT fk_employee_manager
FOREIGN KEY (MANAGER_ID) REFERENCES MANAGER (ID);
)";

const std::string Queries::ALTER_SCHEDULE_ADD_FOREIGN_KEYS = 
R"(
-- No foreign keys to add
)";

const std::string Queries::ALTER_EMPLOYEE_CHANGE_ADD_FOREIGN_KEYS = 
R"(
ALTER TABLE EMPLOYEE_CHANGE ADD CONSTRAINT fk_employee_change_employee
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (ID);

ALTER TABLE EMPLOYEE_CHANGE ADD CONSTRAINT fk_employee_change_manager
FOREIGN KEY (MANAGER_ID) REFERENCES MANAGER (ID);
)";

const std::string Queries::ALTER_JOB_POSITION_ADD_FOREIGN_KEYS = 
R"(
-- No foreign keys to add
)";
